# Generated by Django 5.1.2 on 2024-11-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckTab',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('city', models.TextField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('slot_of_day', models.TextField(blank=True, choices=[('FN', 'Forenoon'), ('AN', 'Afternoon'), ('EVE', 'Evening')], max_length=3, null=True)),
                ('event', models.TextField(blank=True, max_length=50, null=True)),
                ('special', models.TextField(blank=True, max_length=50, null=True)),
                ('temperature', models.IntegerField(blank=True, null=True)),
                ('condition', models.TextField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
