# Generated by Django 5.1.2 on 2024-11-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test11app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checktab',
            name='date',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
