# Generated by Django 5.1.2 on 2024-11-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test11app', '0002_alter_checktab_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='checktab',
            name='original_condition',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
