# Generated by Django 5.1.2 on 2024-11-14 07:57

import Test11app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test11app', '0004_checktab_is_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='checktab',
            name='is_missed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checktab',
            name='priority',
            field=models.IntegerField(default=Test11app.models.generate_priority),
        ),
    ]
