# Generated by Django 5.1.2 on 2024-11-21 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test11app', '0005_checktab_is_missed_checktab_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checktab',
            name='is_missed',
        ),
        migrations.RemoveField(
            model_name='checktab',
            name='priority',
        ),
    ]
